### ISSUE TITLE
How to flip the polarities for those opinion words with original 'neutral' labels?

### ISSUE THREAD

**Issue by scofield7419** [zhijing-jin/ARTS_TestSet#3]
With respect to the opinion polarity modification, I find that in the article you placed most emphasis on how to operate on those opinion words with 'negative' or 'positive' labels. But I do notice in your dataset that the 'neutral' polarities can be flipped into other labels. And this part is not mentioned in the paper.

If using the same method, e.g., looking up WordNet for an antonym as its replacement, how to determine the sentiment polarity for this antonym when its origin is a 'neutral' term?

So my technical question is: **_How did you flip the polarities for those opinion words with original 'neutral' labels_**?

**Comment by zhijing-jin** [comment]
Hi, thanks for the very good question. Let's look into a typical example of "neutral" sentiment:
"sentence": "Once for **dinner** and once for **brunch**.",
        "term_list": {
            "1099_0": {
                "id": "1099_0",
                "polarity": "neutral",
                "term": "dinner",
                "from": 9,
                "to": 15
            },
            "1099_1": {
                "id": "1099_1",
                "polarity": "neutral",
                "term": "brunch",
                "from": 29,
                "to": 35
            }
        },


Here, the aspect terms "dinner" and "brunch" are basically irrelevant for sentiments. So we decide to do the followings:

1. For _RevTgt_, we can barely have a consistent strategy to deal with all neutral expressions, so we decide to skip the neutral aspects. (E.g., it is hard to imagine how to appropriately change the above sentence "Once for dinner and once for brunch" from neutral to positive or negative)
2. For _RevNon_, same here, we only flip positive and negative aspects, and keep neutral aspects as it is.
3. For _AddDiff_, if the target aspect is neutral, then we can append either positive or negative aspects to it

Hope this explanation helps! (You are also welcome to innovate new methods to deal with neutral terms. They are quite special.)

**Comment by scofield7419** [comment]
Big thank for your reply! I think sometimes adding negation words for neutral expressions may be an option.

**Comment by zhijing-jin** [comment]
Yeah, reasonable. Perhaps people need to categorize the neutral cases (e.g., sometimes it is relevant such as "mediocre _food_", and sometimes irrelevant such as "I had a _meal_"), and for cases like "mediocre _food_" it can be addressed properly.
