### ISSUE TITLE
 The version of allennlp?

### ISSUE THREAD

**Issue by BD-MF** [zhijing-jin/ARTS_TestSet#5]
Recently I am reading your article and trying to run your code, but I always encounter all kinds of problems with allennlp. What is the version of allennlp?

**Comment by helldog-star** [comment]
Hi, I have the same question with you, did you find the answer?

**Comment by helldog-star** [comment]
allennlp-2.5.0 with the Predictor https://s3-us-west-2.amazonaws.com/allennlp/models/elmo-constituency-parser-2020.02.10.tar.gz could work

**Comment by zhijing-jin** [comment]
Thank you for figuring this out! We have forgot which version we used. I will post this to our README page, so that future researchers will refer to this version of the allennlp.

**Comment by helldog-star** [comment]
> Thank you for figuring this out! We have forgot which version we used. I will post this to our README page, so that future researchers will refer to this version of the allennlp.

You are welcome. By the way, the augmentation train/dev data I generated is not as good as ARTS's. If you constructed the corresponding training/developing sets as well, could they be available?：）
